Console.WriteLine("*** Ma liste todo ***");
Console.WriteLine("Aujourd'hui je dois faire:");
Console.WriteLine("\t  -Apprendre le C#");
Console.WriteLine("\t  -Apprendre à utiliser Visual Studio");
Console.WriteLine("\t  -Comprendre l'affichage \"Console\"");
Console.WriteLine("\t  -Créer mon répertoire \"c:\\MesExercices\\\" pour les ranger");
Console.WriteLine("\t  -Apprécier les fonctionnalités du C#");
Console.WriteLine();
Console.WriteLine();
Console.WriteLine("Appuyer sur une touche pour continuer...");